#use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MAGBXMSDK_Example' do
  pod 'MAGBXMSDK', :path => '../'

  target 'MAGBXMSDK_Tests' do
    inherit! :search_paths

    
  end
end
